<br>

## 1. Numpy Recap

In [2]:
import numpy as np

<br>

#### np.ndarray 만들기

In [5]:
v1 = np.array([1, 2, 3, 4]) # 배열(Array)
v1

array([1, 2, 3, 4])

In [7]:
type(v1) # 어떤 자료형일까요?

numpy.ndarray

In [9]:
v1.dtype # d(ata)-type

dtype('int64')

In [11]:
v2 = np.array([1,2,4.3,10, '안녕'])
v2

array(['1', '2', '4.3', '10', '안녕'], dtype='<U32')

In [13]:
v1.shape # '모양'을 영어로?

(4,)

In [15]:
sample_matrix = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
sample_matrix.shape

(3, 3)

In [19]:
sample_matrix[0]

array([1, 2, 3])

In [21]:
sample_matrix [ 0, 0 ]

1

In [23]:
sample_matrix [ 0:2, 1:3] # 1, 2행 2, 3열

array([[2, 3],
       [5, 6]])

In [25]:
sample_matrix [  : , 2 ] # 모든 행에 걸쳐서 세 번째 열에 있는 아이템까지

array([3, 6, 9])

In [27]:
sample_matrix [ : , : ]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
v1 = np.array([[1, 2, 3], [4, 5, 6]]) # 진짜 행렬 만들기
v1

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
v1.shape

(2, 3)

<br>

#### np.arange & np.reshape

In [34]:
v1 = np.arange (5) # 'a'rray of 'range'
v1

array([0, 1, 2, 3, 4])

In [36]:
for i in range(5):
    print (i)

0
1
2
3
4


In [38]:
for i in range(5, 15, 2): # 5부터 15 앞까지, 스텝은 2로
    print(i) 

5
7
9
11
13


In [40]:
v2 = np.arange(1, 10, 2)
v2

array([1, 3, 5, 7, 9])

In [42]:
#Broadcasting

v4 = np.arange(1, 10, 2) ** 2 # 제곱 연산자가 무엇이었죠?
v4

array([ 1,  9, 25, 49, 81])

In [44]:
[1, 3, 5, 7, 9] * 2

[1, 3, 5, 7, 9, 1, 3, 5, 7, 9]

In [46]:
v1 = np.arange(12)
v1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
v2 = v1.reshape(2, 6) # 2행 6열 # '모양'을 '다시' 고치다
v2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [50]:
v2 = v1.reshape(4, -1) # reshape에서 -1은 그 차원은 알아서 계산해달라는 뜻
v2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
v3 = v1.reshape(2, 6, order='F') # 열 단위로 채우기 # C & Fortran
v3

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

In [54]:
# Method-chanining

v1 = np.arange(12).reshape(2, 6).reshape(4, -1)
v1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

<br>

#### np.ndarray 의 사칙연산

In [57]:
v1 = np.arange(1, 5).reshape(2, 2)
v1

array([[1, 2],
       [3, 4]])

In [59]:
np.max(v1)

4

In [61]:
np.max(v1, axis=0) # axis=0이 열 방향(디폴트), axis=1은 행 방향 

array([3, 4])

In [63]:
np.min(v1)

1

In [65]:
np.mean(v1) # 평균

2.5

In [67]:
np.std(v1) # 표준편차

1.118033988749895

<br>

#### 행렬 간의 사칙연산

In [70]:
v1 # 1, 2, 3, 4는 행렬에서 element

array([[1, 2],
       [3, 4]])

In [72]:
np.add(v1, v1) # 더하기 (element-wise add)

array([[2, 4],
       [6, 8]])

In [74]:
np.subtract(v1, v1) # 빼기

array([[0, 0],
       [0, 0]])

In [76]:
np.multiply(v1, v1) # 곱하기 (element-wise multiply)

array([[ 1,  4],
       [ 9, 16]])

In [78]:
np.dot(v1, v1) # 행렬곱 (dot-product)

array([[ 7, 10],
       [15, 22]])

<br>

## 2. Pandas Recap

In [3]:
import pandas as pd

<br>

#### Series

In [6]:
# Key(index) 값이 있는 리스트

a = pd.Series([1, 3, 5, 7]) # Series는 1차원
a

0    1
1    3
2    5
3    7
dtype: int64

In [8]:
a.values # Series.value는 변수, dict.values()는 함수

array([1, 3, 5, 7])

In [10]:
a.index

RangeIndex(start=0, stop=4, step=1)

In [12]:
a2 = pd.Series([1, 3, 5, 7], index=['a', 'b', 'c', 'd'])
a2

a    1
b    3
c    5
d    7
dtype: int64

<br>

#### DataFrame

In [102]:
df = pd.read_excel('cosmetics_.xlsx')
df.head()

gender  marriage  edu  job  mincome  aware  count  amount  decision  \
0       1         1    4    1        2      2      1   11000         2   
1       2         1    4    9        2      1      4   30000         1   
2       2         2    4    4        3      1      6  100000         3   
3       2         2    4    7        5      2      6   65000         3   
4       1         2    6    6        5      2      2   50000         2   

   propensity  skin  promo  location  satisf_b  satisf_i  satisf_al  \
0           1     1      1         2         5         2          2   
1           1     3      2         3         2         3          3   
2           2     3      2         2         4         5          4   
3           2     5      2         3         3         4          4   
4           2     3      2         3         3         3          3   

   repurchase  
0           2  
1           4  
2           4  
3           4  
4           3

In [104]:
df['amount'] # 평균 1회 구매 비용

0        11000
1        30000
2       100000
3        65000
4        50000
        ...   
242       4000
243     150000
244     100000
245      20000
246    1000000
Name: amount, Length: 247, dtype: int64

In [106]:
df.amount # 열 이름에 한글이나 공백이 포함되지 않은 경우

0        11000
1        30000
2       100000
3        65000
4        50000
        ...   
242       4000
243     150000
244     100000
245      20000
246    1000000
Name: amount, Length: 247, dtype: int64

In [108]:
df.columns

Index(['gender', 'marriage', 'edu', 'job', 'mincome', 'aware', 'count',
       'amount', 'decision', 'propensity', 'skin', 'promo', 'location',
       'satisf_b', 'satisf_i', 'satisf_al', 'repurchase'],
      dtype='object')

In [110]:
df.index

RangeIndex(start=0, stop=247, step=1)

In [112]:
df.head(3)

gender  marriage  edu  job  mincome  aware  count  amount  decision  \
0       1         1    4    1        2      2      1   11000         2   
1       2         1    4    9        2      1      4   30000         1   
2       2         2    4    4        3      1      6  100000         3   

   propensity  skin  promo  location  satisf_b  satisf_i  satisf_al  \
0           1     1      1         2         5         2          2   
1           1     3      2         3         2         3          3   
2           2     3      2         2         4         5          4   

   repurchase  
0           2  
1           4  
2           4

In [114]:
# # DataFrame에서 하나의 Cell에 해당하는 값을 얻어내는 4가지 방법

df['amount'][0] # 열에 접근 후 Series의 index로 접근
df.loc[0]['amount'] # 행에 접근 후 Series의 index로 접근
df.loc[0, 'amount'] # 행 이름과 열 이름을 지정하여 접근 (loc 활용)
df.at[0, 'amount'] # 행 이름과 열 이름을 지정하여 접근 (at 활용) , 이 방법 추천!
df.iloc[0, 7] # indexed-location 기반으로 index number 기준 행 & 열 지정하여 접근 

11000

In [116]:
df.at[3, 'amount'] # located "at" 3 & 'amount'

65000

In [118]:
df.loc[3, 'amount']

65000

In [120]:
df['total_payment'] = df['amount'] * df['count'] # 평균 1회 구매 비용 / 구매 횟수 == 총 연 구매 금액
df.head()

gender  marriage  edu  job  mincome  aware  count  amount  decision  \
0       1         1    4    1        2      2      1   11000         2   
1       2         1    4    9        2      1      4   30000         1   
2       2         2    4    4        3      1      6  100000         3   
3       2         2    4    7        5      2      6   65000         3   
4       1         2    6    6        5      2      2   50000         2   

   propensity  skin  promo  location  satisf_b  satisf_i  satisf_al  \
0           1     1      1         2         5         2          2   
1           1     3      2         3         2         3          3   
2           2     3      2         2         4         5          4   
3           2     5      2         3         3         4          4   
4           2     3      2         3         3         3          3   

   repurchase  total_payment  
0           2          11000  
1           4         120000  
2           4         600000  
3           4         390000  
4           3         100000

In [122]:
df.insert(8, 'total_payment_', df['amount'] * df['count']) # index 기준으로 8번 열에 새로운 열을 "삽입"
df.head()

gender  marriage  edu  job  mincome  aware  count  amount  total_payment_  \
0       1         1    4    1        2      2      1   11000           11000   
1       2         1    4    9        2      1      4   30000          120000   
2       2         2    4    4        3      1      6  100000          600000   
3       2         2    4    7        5      2      6   65000          390000   
4       1         2    6    6        5      2      2   50000          100000   

   decision  propensity  skin  promo  location  satisf_b  satisf_i  satisf_al  \
0         2           1     1      1         2         5         2          2   
1         1           1     3      2         3         2         3          3   
2         3           2     3      2         2         4         5          4   
3         3           2     5      2         3         3         4          4   
4         2           2     3      2         3         3         3          3   

   repurchase  total_payment  
0           2          11000  
1           4         120000  
2           4         600000  
3           4         390000  
4           3         100000

In [124]:
del df['total_payment']
del df['total_payment_']

In [126]:
df_gender = df[df['gender'] == 1] 
df_gender.head()

df_gender.describe()

gender    marriage         edu         job     mincome       aware  \
count   132.0  132.000000  132.000000  132.000000  132.000000  132.000000   
mean      1.0    1.704545    4.590909    4.098485    4.136364    4.219697   
std       0.0    0.457985    1.666713    2.157394    1.614688    6.782684   
min       1.0    1.000000    2.000000    1.000000    1.000000    1.000000   
25%       1.0    1.000000    4.000000    3.000000    3.000000    2.000000   
50%       1.0    2.000000    4.000000    4.000000    4.000000    2.000000   
75%       1.0    2.000000    6.000000    4.250000    6.000000    2.000000   
max       1.0    2.000000    8.000000   10.000000    6.000000   31.000000   

            count        amount    decision  propensity        skin  \
count  132.000000  1.320000e+02  132.000000  132.000000  132.000000   
mean     3.227273  1.277576e+05    2.371212    1.909091    2.621212   
std      3.242351  4.484804e+05    0.775634    0.635520    1.422450   
min      1.000000  3.000000e+03    1.000000    1.000000    1.000000   
25%      1.000000  3.000000e+04    2.000000    1.750000    1.000000   
50%      2.000000  5.000000e+04    3.000000    2.000000    3.000000   
75%      3.000000  1.000000e+05    3.000000    2.000000    4.000000   
max     20.000000  5.000000e+06    3.000000    3.000000    5.000000   

            promo    location    satisf_b    satisf_i   satisf_al  repurchase  
count  132.000000  132.000000  132.000000  132.000000  132.000000  132.000000  
mean     1.992424    2.545455    2.840909    3.378788    3.439394    3.462121  
std      0.886680    1.043801    0.789526    0.796273    0.712565    0.755694  
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000  
25%      1.000000    2.000000    2.000000    3.000000    3.000000    3.000000  
50%      2.000000    3.000000    3.000000    3.000000    3.000000    4.000000  
75%      2.000000    3.000000    3.000000    4.000000    4.000000    4.000000  
max      4.000000    5.000000    5.000000    5.000000    5.000000    5.000000

In [136]:
df_reacount = df[ (df['count'] < 10) & (df['count'] >= 1) ] # 연 구매 횟수 1회 ~ 9회 이하 & 각 조건식을 ()로 감싸줘야 합니다.
df_reacount.head()

gender  marriage  edu  job  mincome  aware  count  amount  decision  \
0       1         1    4    1        2      2      1   11000         2   
1       2         1    4    9        2      1      4   30000         1   
2       2         2    4    4        3      1      6  100000         3   
3       2         2    4    7        5      2      6   65000         3   
4       1         2    6    6        5      2      2   50000         2   

   propensity  skin  promo  location  satisf_b  satisf_i  satisf_al  \
0           1     1      1         2         5         2          2   
1           1     3      2         3         2         3          3   
2           2     3      2         2         4         5          4   
3           2     5      2         3         3         4          4   
4           2     3      2         3         3         3          3   

   repurchase  
0           2  
1           4  
2           4  
3           4  
4           3

In [142]:
type(df['edu'])

pandas.core.series.Series

In [148]:
df['edu'].values

array([4, 4, 4, 4, 6, 2, 6, 6, 4, 4, 7, 2, 4, 4, 4, 4, 8, 3, 2, 4, 2, 4,
       4, 2, 3, 4, 4, 4, 8, 4, 7, 4, 2, 8, 4, 8, 6, 2, 4, 2, 4, 8, 4, 8,
       4, 8, 4, 4, 4, 4, 2, 2, 4, 4, 4, 4, 8, 4, 4, 8, 4, 4, 4, 2, 4, 4,
       7, 4, 4, 6, 2, 2, 4, 4, 4, 4, 4, 4, 4, 2, 8, 4, 4, 7, 6, 6, 4, 6,
       6, 7, 6, 4, 4, 4, 2, 4, 8, 4, 4, 4, 8, 4, 4, 2, 8, 6, 6, 4, 4, 4,
       2, 4, 4, 4, 2, 8, 6, 6, 4, 4, 4, 4, 4, 8, 6, 3, 2, 7, 2, 4, 4, 2,
       4, 2, 8, 6, 4, 4, 4, 4, 4, 4, 4, 4, 6, 7, 3, 4, 4, 6, 6, 4, 4, 7,
       4, 7, 4, 4, 8, 4, 3, 3, 4, 4, 4, 4, 8, 7, 8, 6, 4, 8, 4, 2, 8, 8,
       4, 7, 7, 4, 3, 4, 2, 4, 5, 4, 8, 8, 4, 2, 4, 4, 8, 6, 2, 2, 8, 4,
       4, 4, 2, 5, 4, 4, 3, 6, 4, 6, 6, 4, 7, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 2, 6, 6, 4, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 6, 7, 2,
       4, 4, 7, 4, 6])

In [154]:
from collections import Counter

Counter(df['edu'].values)

Counter({4: 136, 2: 30, 6: 29, 8: 26, 7: 15, 3: 9, 5: 2})

In [156]:
from collections import Counter

counted = Counter(df['edu'].values) #dict to pd.Series

counted.keys()

dict_keys([4, 6, 2, 7, 8, 3, 5])

In [160]:
from collections import Counter

counted = Counter(df['edu'].values) #dict to pd.Series

pd.Series(data = counted.values(), index= counted.keys())

4    136
6     29
2     30
7     15
8     26
3      9
5      2
dtype: int64

In [144]:
df['edu'].value_counts()

edu
4    136
2     30
6     29
8     26
7     15
3      9
5      2
Name: count, dtype: int64

In [162]:
df['edu'].value_counts(sort=False)

edu
4    136
6     29
2     30
7     15
8     26
3      9
5      2
Name: count, dtype: int64

In [166]:
def num_to_character(data):
    if data == 1:
        return 'male'
    else:
        return 'female'

In [171]:
df['gender_2'] = df['gender'].apply(num_to_character) # 적용하다
df.head()

gender  marriage  edu  job  mincome  aware  count  amount  decision  \
0       1         1    4    1        2      2      1   11000         2   
1       2         1    4    9        2      1      4   30000         1   
2       2         2    4    4        3      1      6  100000         3   
3       2         2    4    7        5      2      6   65000         3   
4       1         2    6    6        5      2      2   50000         2   

   propensity  skin  promo  location  satisf_b  satisf_i  satisf_al  \
0           1     1      1         2         5         2          2   
1           1     3      2         3         2         3          3   
2           2     3      2         2         4         5          4   
3           2     5      2         3         3         4          4   
4           2     3      2         3         3         3          3   

   repurchase gender_2  
0           2     male  
1           4   female  
2           4   female  
3           4   female  
4           3     male

In [175]:
df['gender_2'] = df['gender'].apply(lambda x : 'male' if x == 1 else 'female')
df.head()

gender  marriage  edu  job  mincome  aware  count  amount  decision  \
0       1         1    4    1        2      2      1   11000         2   
1       2         1    4    9        2      1      4   30000         1   
2       2         2    4    4        3      1      6  100000         3   
3       2         2    4    7        5      2      6   65000         3   
4       1         2    6    6        5      2      2   50000         2   

   propensity  skin  promo  location  satisf_b  satisf_i  satisf_al  \
0           1     1      1         2         5         2          2   
1           1     3      2         3         2         3          3   
2           2     3      2         2         4         5          4   
3           2     5      2         3         3         4          4   
4           2     3      2         3         3         3          3   

   repurchase gender_2  
0           2     male  
1           4   female  
2           4   female  
3           4   female  
4           3     male